
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DistributedInformationSystems
{

using System;
    using System.Collections.Generic;
    
public partial class StudetnCompositionByYear
{

    public int Id { get; set; }

    public decimal Hispanic { get; set; }

    public decimal NonHispanic { get; set; }

    public decimal White { get; set; }

    public decimal AfricanAmerican { get; set; }

    public decimal Asian { get; set; }

    public decimal Hawaiian { get; set; }

    public decimal MultiRacial { get; set; }

    public decimal Unknown { get; set; }

    public int SchoolYearId { get; set; }

    public string SchoolName { get; set; }

}

}
